'use strict';
/**
 * Tunnel manager — the "no port forwarding" feature.
 *
 * Three providers, all of which work without owning a domain or a website:
 *
 *  frp      own relay (any VPS running frps). This is the monetisable path:
 *           point it at your relay and hand out subdomains later. Also works
 *           today with a cheap VPS + IP:port, no DNS required.
 *  playit   bring-your-own playit.gg agent binary — free public service, the
 *           user only has to point us at their agent.
 *  custom   any tunnel CLI: we run your command and scrape the public address
 *           out of its output.
 *
 * IP preservation caveat (documented in the UI), because it bites people:
 * a plain TCP relay NATs every player to the relay host, so IP bans and
 * IP-based plugins see one address. frp can add PROXY protocol with
 * transport.proxyProtocolVersion, which requires a server-side plugin
 * (HAProxyDetector) to be readable by Minecraft.
 */
const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');
const { getDirs } = require('../core/paths');
const { createLogger, ensureDir, exists, rmrf, writeText } = require('../core/util');
const { fetchJSON, download, extractArchive } = require('../core/http');
const instances = require('../servers/instances');
const license = require('../licensing/license');

const log = createLogger('tunnel');

const FRP_REPO = 'https://api.github.com/repos/fatedier/frp/releases/latest';
const running = new Map();   // id -> { proc, provider, info }

const ADDRESS_PATTERNS = [
  /([a-z0-9][a-z0-9-]*(?:\.[a-z0-9-]+)*\.playit\.gg(?::\d+)?)/i,
  /([a-z0-9][a-z0-9.-]*\.(?:ngrok|trycloudflare|localtunnel|serveo|bore)\.[a-z]+(?::\d+)?)/i,
  /\b(\d{1,3}(?:\.\d{1,3}){3}:\d{2,5})\b/
];

function scrapeAddress(text, customRegex = null) {
  if (customRegex) {
    try {
      const m = text.match(new RegExp(customRegex, 'i'));
      if (m) return m[1] || m[0];
    } catch { /* bad user regex */ }
  }
  for (const re of ADDRESS_PATTERNS) {
    const m = text.match(re);
    if (m) return m[1];
  }
  return null;
}

async function frpAsset() {
  const rel = await fetchJSON(FRP_REPO, { headers: { Accept: 'application/vnd.github+json' } });
  const version = String(rel.tag_name || '').replace(/^v/, '');
  if (!version) throw new Error('Could not read the latest frp release');
  const osTag = process.platform === 'win32' ? 'windows' : (process.platform === 'darwin' ? 'darwin' : 'linux');
  const archTag = process.arch === 'arm64' ? 'arm64' : (process.arch === 'ia32' ? '386' : 'amd64');
  const wanted = `frp_${version}_${osTag}_${archTag}`;
  const asset = (rel.assets || []).find((a) => a.name && a.name.startsWith(wanted));
  if (!asset) throw new Error(`No frp build for ${osTag}/${archTag} in release ${version}`);
  return { version, url: asset.browser_download_url, name: asset.name };
}

async function ensureFrpc(onLog) {
  const { tools } = getDirs();
  const asset = await frpAsset();
  const dir = path.join(tools, `frp-${asset.version}`);
  const binName = process.platform === 'win32' ? 'frpc.exe' : 'frpc';
  const bin = path.join(dir, binName);
  if (exists(bin)) return bin;

  ensureDir(dir);
  const archive = path.join(getDirs().cache, asset.name);
  if (onLog) onLog(`Downloading frp client ${asset.version}…`);
  await download(asset.url, archive);
  await extractArchive(archive, dir);
  // some archives nest the binaries one level deep
  if (!exists(bin)) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        const nested = path.join(dir, entry.name, binName);
        if (exists(nested)) return nested;
      }
    }
    throw new Error(`frpc binary not found after extracting ${asset.name}`);
  }
  if (process.platform !== 'win32') {
    try { fs.chmodSync(bin, 0o755); } catch { /* ignore */ }
  }
  return bin;
}

function writeFrpConfig(meta, file) {
  const t = meta.tunnel || {};
  const serverAddr = t.serverAddr || 'CHANGE-ME';
  const serverPort = Number(t.serverPort || 7000);
  const remotePort = Number(t.remotePort || 25566);
  const lines = [
    '# Generated by MCServerSmith — frp client configuration',
    `serverAddr = "${serverAddr}"`,
    `serverPort = ${serverPort}`,
    ''
  ];
  if (t.token) {
    lines.push('auth.method = "token"', `auth.token = "${t.token}"`, '');
  }
  if (t.proxyProtocol) {
    lines.push('# Preserves the original player IP (server needs the HAProxyDetector plugin)',
      'transport.proxyProtocolVersion = "v2"', '');
  }
  lines.push(
    '[[proxies]]',
    `name = "mcss-${meta.id}"`,
    'type = "tcp"',
    'localIP = "127.0.0.1"',
    `localPort = ${meta.port}`,
    `remotePort = ${remotePort}`,
    ''
  );
  writeText(file, lines.join('\n'));
  return file;
}

function spawnTunnel(name, cmd, args, { cwd, onLog, addressRegex = null, provider }) {
  const proc = spawn(cmd, args, { cwd, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  const state = { proc, provider, info: null, address: null, lastLines: [] };

  const handle = (buf) => {
    const text = buf.toString('utf8');
    for (const raw of text.split(/\r?\n/)) {
      const line = raw.replace(/\u001b\[[0-9;]*m/g, '').trim();
      if (!line) continue;
      state.lastLines.push(line);
      if (state.lastLines.length > 100) state.lastLines.shift();
      if (onLog) onLog(`[${provider}] ${line}`);
      if (!state.address) {
        const addr = scrapeAddress(line, addressRegex);
        if (addr) {
          state.address = normalizeAddress(addr);
          if (onLog) onLog(`[${provider}] public address: ${state.address}`);
        }
      }
    }
  };
  proc.stdout.on('data', handle);
  proc.stderr.on('data', handle);
  proc.on('error', (err) => { state.error = err.message; if (onLog) onLog(`[${provider}] error: ${err.message}`); });
  return state;
}

function normalizeAddress(raw) {
  const text = String(raw).trim();
  if (/^\d{1,3}(\.\d{1,3}){3}$/.test(text)) return `${text}:25565`;
  if (text.includes('.') && !text.includes('.gg') && !/\.(?:ngrok|trycloudflare|localtunnel|serveo|bore)/.test(text) && !text.includes(':')) {
    return `${text}:25565`;
  }
  return text;
}

/**
 * @returns {Promise<{provider:string, address:string|null, detail:object}>}
 */
async function start(manager, id) {
  const meta = instances.read(id);
  const t = meta.tunnel || { provider: 'none' };
  if (t.provider === 'none') return null;
  if (running.has(id)) return running.get(id).info;

  license.requireFeature('tunnel');

  const p = instances.instancePaths(id);
  const workDir = path.join(p.dir, 'tmp');
  ensureDir(workDir);
  const onLog = (line) => manager._emit('log', id, { line, level: 'plain', event: { type: 'tunnel' } });

  let state;
  if (t.provider === 'frp') {
    const bin = await ensureFrpc(onLog);
    const cfg = writeFrpConfig(meta, path.join(workDir, 'frpc.toml'));
    onLog(`Starting frp tunnel to ${t.serverAddr}:${t.serverPort || 7000}…`);
    state = spawnTunnel('frp', bin, ['-c', cfg], { cwd: workDir, onLog, provider: 'frp' });
    state.info = {
      provider: 'frp',
      address: t.publicHost ? `${t.publicHost}:${t.remotePort || 25566}` : null,
      relay: `${t.serverAddr}:${t.serverPort || 7000}`,
      remotePort: t.remotePort || 25566,
      ipPreserved: !!t.proxyProtocol
    };
    // frp is deterministic: the public address is known up front
    if (state.address && !state.info.address) state.info.address = state.address;
  } else if (t.provider === 'playit') {
    if (!t.playitPath || !exists(t.playitPath)) {
      throw new Error('Point "playit agent path" at your downloaded playit.gg agent binary in the server settings.');
    }
    onLog('Starting playit.gg agent…');
    state = spawnTunnel('playit', t.playitPath, ['start'], { cwd: workDir, onLog, provider: 'playit' });
    state.info = { provider: 'playit', address: null, relay: 'playit.gg', ipPreserved: false };
  } else if (t.provider === 'custom') {
    if (!t.customCommand) throw new Error('No custom tunnel command configured');
    const isWin = process.platform === 'win32';
    const cmd = isWin ? (process.env.ComSpec || 'cmd.exe') : '/bin/sh';
    const args = isWin ? ['/c', t.customCommand] : ['-c', t.customCommand];
    onLog(`Starting custom tunnel: ${t.customCommand}`);
    state = spawnTunnel('custom', cmd, args, {
      cwd: workDir, onLog, addressRegex: t.customRegex || null, provider: 'custom'
    });
    state.info = { provider: 'custom', address: null, ipPreserved: false };
  } else {
    throw new Error(`Unknown tunnel provider ${t.provider}`);
  }

  running.set(id, state);

  // give the client a moment and pick up the address if it announced one
  await new Promise((r) => setTimeout(r, 2500));
  if (state.address) state.info.address = state.address;

  return state.info;
}

async function stop(id) {
  const state = running.get(id);
  if (!state) return false;
  try {
    if (process.platform !== 'win32') {
      try { process.kill(-state.proc.pid, 'SIGTERM'); } catch { /* ignore */ }
    }
    state.proc.kill();
  } catch { /* ignore */ }
  running.delete(id);
  log.info(`tunnel stopped for ${id}`);
  return true;
}

function status(id) {
  const state = running.get(id);
  if (!state) return { running: false };
  return {
    running: true,
    provider: state.provider,
    address: state.address,
    error: state.error || null,
    tail: state.lastLines.slice(-10)
  };
}

function runningCount() {
  return running.size;
}

module.exports = { start, stop, status, runningCount, scrapeAddress, ensureFrpc, FRP_REPO };
