'use strict';
/** JVM flags. Aikar's flags are the de-facto standard for Minecraft servers. */
const AIKAR_FLAGS = [
  '-XX:+UseG1GC',
  '-XX:+ParallelRefProcEnabled',
  '-XX:MaxGCPauseMillis=200',
  '-XX:+UnlockExperimentalVMOptions',
  '-XX:+DisableExplicitGC',
  '-XX:+AlwaysPreTouch',
  '-XX:G1NewSizePercent=30',
  '-XX:G1MaxNewSizePercent=40',
  '-XX:G1HeapRegionSize=8M',
  '-XX:G1ReservePercent=20',
  '-XX:G1HeapWastePercent=5',
  '-XX:G1MixedGCCountTarget=4',
  '-XX:InitiatingHeapOccupancyPercent=15',
  '-XX:G1MixedGCLiveThresholdPercent=90',
  '-XX:G1RSetUpdatingPauseTimePercent=5',
  '-XX:SurvivorRatio=32',
  '-XX:+PerfDisableSharedMem',
  '-XX:MaxTenuringThreshold=1'
];

function xmsFor(memoryMB) {
  return Math.max(512, Math.min(memoryMB, Math.round(memoryMB / 2)));
}

/** Flags for a directly-launched jar. */
function jarFlags({ memoryMB = 4096, jvmArgs = [], useAikar = true, extra = [] } = {}) {
  const flags = [`-Xms${xmsFor(memoryMB)}M`, `-Xmx${memoryMB}M`];
  if (useAikar) flags.push(...AIKAR_FLAGS);
  flags.push(...(jvmArgs || []), ...(extra || []));
  return flags;
}

/** Contents of user_jvm_args.txt for script-mode servers (Forge/NeoForge). */
function userJvmArgsFile({ memoryMB = 4096, jvmArgs = [], useAikar = true } = {}) {
  const flags = jarFlags({ memoryMB, jvmArgs, useAikar });
  return ['# Generated by MCServerSmith — JVM flags for this server.', ...flags, ''].join('\n');
}

module.exports = { AIKAR_FLAGS, jarFlags, userJvmArgsFile, xmsFor };
